#!/usr/bin/env python3
"""Convert one binary file into a C++ PROGMEM header."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re


def cpp_identifier(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", value):
        raise argparse.ArgumentTypeError("variable must be a C++ identifier")
    return value


def storage_values(data: bytes, mode: str) -> tuple[str, list[int], int]:
    if mode == "uint8":
        return "uint8_t", list(data), 2
    byteorder = {"uint32-le": "little", "uint32-be": "big"}[mode]
    padded = data + bytes(-len(data) % 4)
    values = [
        int.from_bytes(padded[i : i + 4], byteorder)
        for i in range(0, len(padded), 4)
    ]
    return "uint32_t", values, 8


def format_literal(value: int, width: int, style: str) -> str:
    decimal = str(value)
    hexadecimal = f"0x{value:0{width}x}"
    if style == "decimal":
        return decimal
    if style == "hex":
        return hexadecimal
    short_hexadecimal = f"0x{value:x}"
    return short_hexadecimal if len(short_hexadecimal) <= len(decimal) else decimal


def format_array(
    name: str,
    data: bytes,
    mode: str,
    literal_style: str,
    layout: str,
) -> str:
    storage_type, values, width = storage_values(data, mode)
    if not values:
        values = [0]
    literals = [format_literal(value, width, literal_style) for value in values]

    if layout == "readable":
        per_line = 12 if mode == "uint8" else 8
        body = "\n".join(
            "    " + ", ".join(literals[i : i + per_line]) + ","
            for i in range(0, len(literals), per_line)
        )
        declaration = (
            f"inline const {storage_type} {name}_storage[] PROGMEM = {{\n{body}\n}};"
        )
    elif layout == "compact":
        per_line = 32 if mode == "uint8" else 16
        body = "\n".join(
            ",".join(literals[i : i + per_line]) + ","
            for i in range(0, len(literals), per_line)
        )
        declaration = (
            f"inline const {storage_type} {name}_storage[] PROGMEM = {{\n{body}\n}};"
        )
    else:
        declaration = (
            f"inline const {storage_type} {name}_storage[] PROGMEM = "
            f"{{{','.join(literals)}}};"
        )

    return (
        f"namespace detail {{\n\n{declaration}\n\n}} // namespace detail\n\n"
        f"inline const uint8_t* const {name} =\n"
        f"    reinterpret_cast<const uint8_t*>(detail::{name}_storage);\n"
        f"inline constexpr size_t {name}_size = {len(data)};"
    )


def namespace_name(value: str) -> str:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*", value):
        raise argparse.ArgumentTypeError("namespace must be a C++ namespace name")
    return value


def format_header(
    namespace: str,
    variable: str,
    source: Path,
    data: bytes,
    mode: str,
    literal_style: str,
    layout: str,
) -> str:
    endian_check = ""
    if mode != "uint8":
        endian = {"uint32-le": "little", "uint32-be": "big"}[mode]
        order = "LITTLE" if endian == "little" else "BIG"
        endian_check = f"""#if defined(__BYTE_ORDER__) && defined(__ORDER_{order}_ENDIAN__) && \\
    __BYTE_ORDER__ != __ORDER_{order}_ENDIAN__
#error "This ROM header requires a {endian}-endian target"
#endif

"""
    return f"""// Generated by make_rom_header.py. Do not edit.
// Source: {source.name}
// Source SHA-256: {hashlib.sha256(data).hexdigest()}
// Storage: {mode}; literals: {literal_style}; layout: {layout}
#pragma once

#include <stddef.h>
#include <stdint.h>

#ifndef PROGMEM
#define PROGMEM
#endif

{endian_check}namespace {namespace} {{

{format_array(variable, data, mode, literal_style, layout)}

}} // namespace {namespace}
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert one binary file into a C++ PROGMEM array header."
    )
    parser.add_argument("input", type=Path, help="binary input file")
    parser.add_argument("-n", "--namespace", type=namespace_name, required=True)
    parser.add_argument("-v", "--variable", type=cpp_identifier, required=True)
    parser.add_argument(
        "--mode",
        choices=("uint8", "uint32-le", "uint32-be"),
        default="uint8",
        help="storage type and target byte order (default: uint8)",
    )
    parser.add_argument(
        "--literal",
        choices=("hex", "decimal", "shortest"),
        default="hex",
        help="integer literal style (default: hex)",
    )
    parser.add_argument(
        "--layout",
        choices=("readable", "compact", "minified"),
        default="readable",
        help="source layout (default: readable)",
    )
    parser.add_argument(
        "-o", "--output", type=Path,
        help="output header (default: <variable>.hpp in the current directory)",
    )
    args = parser.parse_args()

    output = args.output or Path(f"{args.variable}.hpp")
    if output.resolve() == args.input.resolve():
        parser.error("output must differ from input")

    data = args.input.read_bytes()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        format_header(
            args.namespace,
            args.variable,
            args.input,
            data,
            args.mode,
            args.literal,
            args.layout,
        ),
        encoding="ascii",
    )
    print(
        f"wrote {output}: {args.variable}={len(data)} bytes "
        f"({args.mode}, {args.literal}, {args.layout})"
    )


if __name__ == "__main__":
    main()
